import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { withQueryClient } from "@/lib/test-utils/query-client";

vi.mock("@/lib/supabase/access-token", () => ({ getAccessToken: vi.fn(async () => "tok") }));

import RutasPage from "./page";

const fetchMock = vi.fn();

const driver = {
  id: "11111111-1111-4111-8111-111111111111",
  authUserId: "auth-driver-1",
  name: "Carlos Pérez",
  email: "carlos@torpreca.gt",
  role: "driver",
  status: "active",
  deactivatedAt: null,
  deactivatedBy: null,
  reviewedAt: null,
  reviewedBy: null,
  createdAt: "2026-09-01T00:00:00.000Z",
  updatedAt: "2026-09-01T00:00:00.000Z",
};

const vehicle = {
  id: "v1",
  plate: "P-123ABC",
  model: "NPR",
  capacity: 10,
  active: true,
  createdAt: "2026-09-01T00:00:00.000Z",
  updatedAt: "2026-09-01T00:00:00.000Z",
};

const pendingRoute = {
  id: "r1",
  code: "R-20260910-01",
  driverId: "11111111-1111-4111-8111-111111111111",
  vehicleId: null,
  createdBy: "admin-1",
  date: "2026-09-10",
  status: "pending",
  plannedKm: 10,
  drivenKm: 0,
  startTime: null,
  endTime: null,
  createdAt: "2026-09-10T00:00:00.000Z",
  updatedAt: "2026-09-10T00:00:00.000Z",
};

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status });
}

function mockFetchRoutes(routes: unknown[]) {
  fetchMock.mockImplementation((url: string) => {
    if (url.startsWith("/api/routes/")) return Promise.resolve(jsonResponse(routes[0]));
    if (url.startsWith("/api/routes")) return Promise.resolve(jsonResponse(routes));
    if (url.startsWith("/api/users")) return Promise.resolve(jsonResponse([driver]));
    if (url.startsWith("/api/vehicles")) return Promise.resolve(jsonResponse([vehicle]));
    throw new Error(`unexpected fetch: ${url}`);
  });
}

beforeEach(() => {
  fetchMock.mockReset();
  vi.stubGlobal("fetch", fetchMock);
});

function renderPage() {
  return render(withQueryClient(<RutasPage />));
}

describe("RutasPage", () => {
  it("shows the empty state when there are no routes", async () => {
    mockFetchRoutes([]);

    renderPage();

    await waitFor(() => expect(screen.getByText("No hay rutas registradas.")).toBeInTheDocument());
  });

  it("lists routes with the driver's name and a status badge", async () => {
    mockFetchRoutes([pendingRoute]);

    renderPage();

    await waitFor(() => expect(screen.getByRole("cell", { name: "Carlos Pérez" })).toBeInTheDocument());
    expect(screen.getByText("R-20260910-01")).toBeInTheDocument();
    expect(screen.getByText("Pendiente")).toBeInTheDocument();
  });

  it("disables 'Crear ruta' until the required fields are filled", async () => {
    mockFetchRoutes([]);

    renderPage();
    await waitFor(() => expect(screen.getByText("No hay rutas registradas.")).toBeInTheDocument());
    // useUsers() (drivers for the dropdown) can resolve after useRoutes() —
    // wait for the option to exist before selecting it, or the <select>
    // silently ignores a value with no matching <option> yet.
    await waitFor(() => expect(screen.getByRole("option", { name: "Carlos Pérez" })).toBeInTheDocument());

    const submitButton = screen.getByRole("button", { name: "Crear ruta" });
    expect(submitButton).toBeDisabled();

    fireEvent.change(screen.getByLabelText("Conductor"), { target: { value: "11111111-1111-4111-8111-111111111111" } });

    await waitFor(() => expect(submitButton).not.toBeDisabled());
  });

  it("creating a route sends the autogenerated code and prepends it to the list", async () => {
    mockFetchRoutes([]);
    fetchMock.mockImplementationOnce(() => Promise.resolve(jsonResponse([])));

    renderPage();
    await waitFor(() => expect(screen.getByText("No hay rutas registradas.")).toBeInTheDocument());
    await waitFor(() => expect(screen.getByRole("option", { name: "Carlos Pérez" })).toBeInTheDocument());

    fireEvent.change(screen.getByLabelText("Conductor"), { target: { value: "11111111-1111-4111-8111-111111111111" } });

    const submitButton = screen.getByRole("button", { name: "Crear ruta" });
    await waitFor(() => expect(submitButton).not.toBeDisabled());

    fetchMock.mockImplementationOnce(() => Promise.resolve(jsonResponse(pendingRoute, 201)));
    fireEvent.click(submitButton);

    await waitFor(() => expect(screen.getByRole("cell", { name: "Carlos Pérez" })).toBeInTheDocument());
    const postCall = fetchMock.mock.calls.find(([, init]) => init?.method === "POST");
    expect(postCall).toBeDefined();
    const body = JSON.parse((postCall?.[1] as RequestInit).body as string);
    expect(body).toMatchObject({ driverId: "11111111-1111-4111-8111-111111111111", vehicleId: null });
    expect(body.code).toMatch(/^R-\d{8}-01$/);
  });

  it("only shows 'Editar' for pending routes", async () => {
    mockFetchRoutes([{ ...pendingRoute, id: "r2", status: "completed" }]);

    renderPage();

    await waitFor(() => expect(screen.getByRole("cell", { name: "Carlos Pérez" })).toBeInTheDocument());
    expect(screen.queryByRole("button", { name: "Editar" })).not.toBeInTheDocument();
  });

  it("editing a pending route submits the changes via PATCH", async () => {
    mockFetchRoutes([pendingRoute]);

    renderPage();
    await waitFor(() => expect(screen.getByRole("cell", { name: "Carlos Pérez" })).toBeInTheDocument());

    fireEvent.click(screen.getByRole("button", { name: "Editar" }));

    const plannedKmInputs = screen.getAllByDisplayValue("10");
    const editInput = plannedKmInputs[plannedKmInputs.length - 1];
    fireEvent.change(editInput, { target: { value: "40" } });

    const saveButton = screen.getByRole("button", { name: "Guardar" });
    await waitFor(() => expect(saveButton).not.toBeDisabled());

    fetchMock.mockImplementationOnce(() =>
      Promise.resolve(jsonResponse({ ...pendingRoute, plannedKm: 40 })),
    );
    fireEvent.click(saveButton);

    await waitFor(() => {
      const patchCall = fetchMock.mock.calls.find(([, init]) => init?.method === "PATCH");
      expect(patchCall).toBeDefined();
    });
    const patchCall = fetchMock.mock.calls.find(([, init]) => init?.method === "PATCH");
    expect(patchCall?.[0]).toBe("/api/routes/r1");
    const body = JSON.parse((patchCall?.[1] as RequestInit).body as string);
    expect(body.plannedKm).toBe(40);
  });
});